# 2020/10/14最新versionを取得
FROM golang:1.15.2-alpine
# アップデートとgitのインストール！！
RUN apk update && apk add git
RUN git config --global user.name namekosiru && git config --global user.email rinjyou0031@toki.waseda.jp
